<?php
/**
 * Demo product catalog data.
 *
 * @package CraftCommerceKit
 */

defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'cck_demo_product_catalog_data' ) ) {
	function cck_demo_product_catalog_data() {
		return array(
			array(
				'name'              => 'Executive Messenger Bag',
				'slug'              => 'executive-messenger-bag',
				'sku'               => 'CCK-DEMO-001',
				'short_description' => 'A structured messenger bag for daily commutes and client meetings.',
				'description'       => 'The Executive Messenger Bag balances refined proportions with durable construction. It is designed for professionals who want a calm, confident silhouette that works across office, travel, and everyday carry scenarios.',
				'regular_price'     => '320',
				'sale_price'        => '280',
				'stock_quantity'    => 18,
				'categories'        => array( 'Bags', 'Office' ),
				'tags'              => array( 'Handmade', 'Premium Leather', 'Best Seller' ),
				'featured_image'    => 'executive-messenger-bag.png',
				'gallery'           => array( 'classic-briefcase.png', 'leather-laptop-sleeve.png' ),
				'upsells'           => array( 'Classic Briefcase', 'Leather Laptop Sleeve' ),
				'cross_sells'       => array( 'Everyday Wallet', 'Slim Card Holder' ),
			),
			array(
				'name'              => 'Classic Briefcase',
				'slug'              => 'classic-briefcase',
				'sku'               => 'CCK-DEMO-002',
				'short_description' => 'A clean briefcase with timeless lines and modern practicality.',
				'description'       => 'Classic Briefcase keeps the presentation sharp, with room for documents, devices, and the small essentials that travel with every meeting. It is a stable everyday carry for premium workwear wardrobes.',
				'regular_price'     => '360',
				'sale_price'        => '',
				'stock_quantity'    => 11,
				'categories'        => array( 'Bags', 'Office' ),
				'tags'              => array( 'Full Grain', 'Premium Leather', 'Limited' ),
				'featured_image'    => 'classic-briefcase.png',
				'gallery'           => array( 'executive-messenger-bag.png', 'signature-journal-cover.png' ),
				'upsells'           => array( 'Leather Laptop Sleeve' ),
				'cross_sells'       => array( 'Signature Journal Cover', 'Travel Organizer' ),
			),
			array(
				'name'              => 'Leather Laptop Sleeve',
				'slug'              => 'leather-laptop-sleeve',
				'sku'               => 'CCK-DEMO-003',
				'short_description' => 'Slim protection for laptops with a clean, minimal profile.',
				'description'       => 'Leather Laptop Sleeve is tailored for devices and the rituals around them. The profile stays slim in a tote or briefcase, while the exterior keeps the language quiet and premium.',
				'regular_price'     => '148',
				'sale_price'        => '128',
				'stock_quantity'    => 22,
				'categories'        => array( 'Office', 'Travel' ),
				'tags'              => array( 'Handmade', 'Full Grain', 'New Arrival' ),
				'featured_image'    => 'leather-laptop-sleeve.png',
				'gallery'           => array( 'classic-briefcase.png', 'everyday-wallet.png' ),
				'upsells'           => array( 'Executive Messenger Bag' ),
				'cross_sells'       => array( 'Everyday Wallet', 'Slim Card Holder' ),
			),
			array(
				'name'              => 'Everyday Wallet',
				'slug'              => 'everyday-wallet',
				'sku'               => 'CCK-DEMO-004',
				'short_description' => 'A compact bifold built for daily essentials and easy access.',
				'description'       => 'Everyday Wallet is a small-format piece with enough structure to age gracefully. It is designed to be the wallet you reach for every day without it feeling ordinary.',
				'regular_price'     => '88',
				'sale_price'        => '',
				'stock_quantity'    => 35,
				'categories'        => array( 'Wallets', 'Accessories' ),
				'tags'              => array( 'Handmade', 'Premium Leather', 'Best Seller' ),
				'featured_image'    => 'everyday-wallet.png',
				'gallery'           => array( 'slim-card-holder.png', 'travel-organizer.png' ),
				'upsells'           => array( 'Slim Card Holder' ),
				'cross_sells'       => array( 'Travel Organizer', 'Signature Journal Cover' ),
			),
			array(
				'name'              => 'Slim Card Holder',
				'slug'              => 'slim-card-holder',
				'sku'               => 'CCK-DEMO-005',
				'short_description' => 'A feather-light card holder for minimal carry.',
				'description'       => 'Slim Card Holder keeps the details tight and refined. It suits streamlined pockets, modern payment routines, and the kind of customer who prefers less volume with the same premium finish.',
				'regular_price'     => '64',
				'sale_price'        => '',
				'stock_quantity'    => 40,
				'categories'        => array( 'Wallets', 'Accessories' ),
				'tags'              => array( 'Full Grain', 'New Arrival' ),
				'featured_image'    => 'slim-card-holder.png',
				'gallery'           => array( 'everyday-wallet.png', 'signature-journal-cover.png' ),
				'upsells'           => array( 'Everyday Wallet' ),
				'cross_sells'       => array( 'Travel Organizer', 'Signature Journal Cover' ),
			),
			array(
				'name'              => 'Artisan Guitar Strap',
				'slug'              => 'artisan-guitar-strap',
				'sku'               => 'CCK-DEMO-006',
				'short_description' => 'A hand-finished guitar strap made for rehearsals and stage use.',
				'description'       => 'Artisan Guitar Strap brings the product system into a different category without changing the language of the brand. It gives musicians a premium accessory that feels crafted, durable, and calm.',
				'regular_price'     => '96',
				'sale_price'        => '84',
				'stock_quantity'    => 16,
				'categories'        => array( 'Music', 'Accessories' ),
				'tags'              => array( 'Handmade', 'Premium Leather', 'Limited' ),
				'featured_image'    => 'artisan-guitar-strap.png',
				'gallery'           => array( 'signature-journal-cover.png', 'travel-organizer.png' ),
				'upsells'           => array( 'Signature Journal Cover' ),
				'cross_sells'       => array( 'Travel Organizer' ),
			),
			array(
				'name'              => 'Travel Organizer',
				'slug'              => 'travel-organizer',
				'sku'               => 'CCK-DEMO-007',
				'short_description' => 'A tidy organizer for passports, cables, and travel essentials.',
				'description'       => 'Travel Organizer keeps documents and everyday carry aligned during transit. It is meant to sit quietly in a carry-on or briefcase while still feeling elevated and considered.',
				'regular_price'     => '124',
				'sale_price'        => '',
				'stock_quantity'    => 20,
				'categories'        => array( 'Travel', 'Office' ),
				'tags'              => array( 'Full Grain', 'Premium Leather', 'Best Seller' ),
				'featured_image'    => 'travel-organizer.png',
				'gallery'           => array( 'executive-messenger-bag.png', 'slim-card-holder.png' ),
				'upsells'           => array( 'Executive Messenger Bag' ),
				'cross_sells'       => array( 'Everyday Wallet', 'Slim Card Holder' ),
			),
			array(
				'name'              => 'Signature Journal Cover',
				'slug'              => 'signature-journal-cover',
				'sku'               => 'CCK-DEMO-008',
				'short_description' => 'A refined cover for notebooks, journals, and planning rituals.',
				'description'       => 'Signature Journal Cover rounds out the catalog with a polished stationery piece. It brings the same craftsmanship language into a smaller format that still feels premium and collectible.',
				'regular_price'     => '78',
				'sale_price'        => '',
				'stock_quantity'    => 28,
				'categories'        => array( 'Office', 'Accessories' ),
				'tags'              => array( 'Handmade', 'Full Grain', 'New Arrival' ),
				'featured_image'    => 'signature-journal-cover.png',
				'gallery'           => array( 'travel-organizer.png', 'leather-laptop-sleeve.png' ),
				'upsells'           => array( 'Travel Organizer' ),
				'cross_sells'       => array( 'Artisan Guitar Strap', 'Slim Card Holder' ),
			),
		);
	}
}

